apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  001-create-schema.sql: |
    CREATE SCHEMA IF NOT EXISTS "Employee";

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mitarbeiterverwaltung-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mitarbeiterverwaltung-db
  template:
    metadata:
      labels:
        app: mitarbeiterverwaltung-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: Administration
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: Password
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U postgres -d Administration"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U postgres -d Administration"]
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
            - name: init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata
        - name: init
          configMap:
            name: postgres-init

---
apiVersion: v1
kind: Service
metadata:
  name: mitarbeiterverwaltung-db
spec:
  selector:
    app: mitarbeiterverwaltung-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
