apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # E-Mail-Adresse für Benachrichtigungen von Let's Encrypt
    email: enkiluzlbel@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret zur Speicherung des ACME-Benutzerkontos
      name: letsencrypt-staging-account-key
    solvers:
      - http01:
          ingress:
            class: nginx